/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCatalogRouteImport } from './routes/api/catalog'
import { Route as ApiGplinksRouteImport } from './routes/api/gplinks'
import { Route as ApiInfoRouteImport } from './routes/api/info'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiStreamRouteImport } from './routes/api/stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogRoute = ApiCatalogRouteImport.update({
  id: '/api/catalog',
  path: '/api/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGplinksRoute = ApiGplinksRouteImport.update({
  id: '/api/gplinks',
  path: '/api/gplinks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInfoRoute = ApiInfoRouteImport.update({
  id: '/api/info',
  path: '/api/info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/gplinks': typeof ApiGplinksRoute
  '/api/info': typeof ApiInfoRoute
  '/api/search': typeof ApiSearchRoute
  '/api/stream': typeof ApiStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/gplinks': typeof ApiGplinksRoute
  '/api/info': typeof ApiInfoRoute
  '/api/search': typeof ApiSearchRoute
  '/api/stream': typeof ApiStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/gplinks': typeof ApiGplinksRoute
  '/api/info': typeof ApiInfoRoute
  '/api/search': typeof ApiSearchRoute
  '/api/stream': typeof ApiStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/catalog'
    | '/api/gplinks'
    | '/api/info'
    | '/api/search'
    | '/api/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/catalog'
    | '/api/gplinks'
    | '/api/info'
    | '/api/search'
    | '/api/stream'
  id:
    | '__root__'
    | '/'
    | '/api/catalog'
    | '/api/gplinks'
    | '/api/info'
    | '/api/search'
    | '/api/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCatalogRoute: typeof ApiCatalogRoute
  ApiGplinksRoute: typeof ApiGplinksRoute
  ApiInfoRoute: typeof ApiInfoRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiStreamRoute: typeof ApiStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog': {
      id: '/api/catalog'
      path: '/api/catalog'
      fullPath: '/api/catalog'
      preLoaderRoute: typeof ApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gplinks': {
      id: '/api/gplinks'
      path: '/api/gplinks'
      fullPath: '/api/gplinks'
      preLoaderRoute: typeof ApiGplinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/info': {
      id: '/api/info'
      path: '/api/info'
      fullPath: '/api/info'
      preLoaderRoute: typeof ApiInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCatalogRoute: ApiCatalogRoute,
  ApiGplinksRoute: ApiGplinksRoute,
  ApiInfoRoute: ApiInfoRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiStreamRoute: ApiStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
